### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by fpinocl** [Qarj/WebInject#1]
Is linux support?.
./webinject.pl -h
Can't exec "cd": No such file or directory at ./webinject.pl line 111.
Use of uninitialized value $cwd in substitution (s///) at ./webinject.pl line 112.

line 111:
my $cwd = (`cd`); ## find current Windows working directory using backtick method
$cwd =~ s/\n//g; ## remove newline character

**Comment by Qarj** [comment]
I am planning to support Linux, it isn't something I have looked at yet. However if people are interested in running it on Linux I can look at it sooner rather than later. It shouldn't be too hard to fix it, there are only a few bits that are hard coded to windows.

**Comment by fpinocl** [comment]
that is cool. Your webinject version is good documented and it have great features.  I will wait your version for linux

**Comment by Qarj** [comment]
@fpinocl I now have all the self tests working on Linux - Fedora 23.

I've updated the installations instructions in the README.

Best to use git clone since it will sort out the line endings.

Can you please try it out and let me know...

**Comment by xoroz** [comment]
I am running on Linux Centos 6 x64 no problem other then something with SSL
 perl, v5.10.1 
Think this was a BUG:
**500 SSL_verify_mode must be a number and not a string**

I changed on webinject.pl
FROM:
 $useragent->ssl_opts(SSL_verify_mode=>'SSL_VERIFY_NONE');
TO:
 $useragent->ssl_opts(SSL_verify_mode=>'0');

and now its working fine :+1:

**Comment by Qarj** [comment]
Yes that changed with a newer version of Perl and libraries. I'm not sure what version. It used to be '0', but I had to change it to 'SSL_VERIFY_NONE'.

Perl v5.10.1 is quite old to be honest - it seems to date from 23 Aug 2009.

Not sure what to do about this - put it in the notes somewhere I guess.

**Comment by Qarj** [comment]
Linux support completed in WebInject 2.0.0
