### ISSUE TITLE
Add verbose to debug

### ISSUE THREAD

**Issue by romsworld** [Qarj/WebInject#14]
Hi,

Is it possible to add a verbose mode to see POST and GET result in the output.

Thanks, !

**Comment by Qarj** [comment]
@romsworld You do realise that the POST and GET result is already logged in the `http.txt` output?

If you wanted to see it live on screen, all you would need to do is open another terminal window and tail it. If this information was written to STDOUT also it would display a huge amount of info.

Can I ask why you want to do this? In 10 years of using WebInject I've never wanted to do such a thing... You should investigate the curl command - this does exactly what you want.

**Comment by Qarj** [comment]
Added the --verbose option to display the request and response as string for each test step.

In the future it may show additional debug information.

**Comment by romsworld** [comment]
Hi Qarj,
I understood that I can see output in http.txt :). Thanks.

**Comment by Qarj** [comment]
Hi Romsworld,

Great – no problem. Actually I added the feature you wanted anyway – there is now a --verbose flag.

What do you use WebInject for?

Best of Luck,

Tim

**Comment by romsworld** [comment]
I m hosting, we check some websites with centreon.

Is it possible to merge config file and test.xml to use only one file ?

**Comment by Qarj** [comment]
Hi Nicolas,

For the way I use WebInject, I wouldn’t want the config and test file in one file.

However for the way you use it, it might be possible since I suspect you do not have much in the config file.

If you send me your config file, I can take a look. You can change the stuff in it so it is anonymous, I just need to see which options you are using.

Cheers,

Tim

**Comment by romsworld** [comment]
It’s very simple

testcasefile>test.xml</testcasefile>
<useragent>Monitoring webinject</useragent>
<timeout>10</timeout>
<globaltimeout>20</globaltimeout>
<reporttype>nagios</reporttype>

Perhaps, I don’t understand the benefit of config file,

**Comment by Qarj** [comment]
Yes I think in your case you don’t have much need for the config file so it is a bit of a pain.

However I use very large config files – the benefit is that you can run the same set of tests against very different environments. In the config file you can set things like the baseurl and environment variables like the username and password needed for various systems in that environment.
