### ISSUE TITLE
Stop the output file generation

### ISSUE THREAD

**Issue by romsworld** [Qarj/WebInject#17]
Hi,

I use webinject with nagios reportype.
/usr/local/nagios/libexec/WebInject/webinject.pl -c /usr/local/nagios/libexec/WebInject/scenarios/test-config.xml

This command generate some file in output directory. How to stop it ?
I test with -n command, but same thing.

Thanks

**Comment by Qarj** [comment]
I will change it to stop all output

**Comment by Qarj** [comment]
@romsworld I've changed it so it does not create files in the output folder under normal use, so now you should no longer see any files created. It will still create the output folder if it does not exist. Also, there are some webinject commands that will create files, however if you do not use these commands, you will not get any files
