### ISSUE TITLE
Encode / Decode

### ISSUE THREAD

**Issue by romsworld** [Qarj/WebInject#21]
Hi,
I would like to understand why the parsreponse result is encore.

I have parseresponseADFS='action="(.*?)"|regex|escape' to find the action=

<body>
    <form name="aspnetForm" method="post" action="/adfs/ls/?wa=wsignin1.0&amp;

---

When I use it on  url="${URLADFS}/{ADFS}"
I have this result : 
POST https://adfs.chateauform.com/%2fadfs%2fls%2f%3fwa%3dwsignin1.0%26amp%

This is encode : "%2fadfs%2fls%2f%3fwa%3dwsignin1.0%26amp%"

I don't understand why.

Thanks

**Comment by Qarj** [comment]
Hi, I've been on annual leave and have just returned.

You need to remove the escape. `escape` escapes the special characters.

```
    parseresponseADFS='action="(.*?)"|regex|'
```
