### ISSUE TITLE
Check for write permission to output locations

### ISSUE THREAD

**Issue by Qarj** [Qarj/WebInject#36]

**Comment by cgoldberg** [comment]
why?

**Comment by Qarj** [comment]
Good point - it is only because of the way I'm using it that this is the case - writing output to `C:\inetpub\wwwroot`. I'll update the issue.

**Comment by cgoldberg** [comment]
best advice would be to run as a user that has access to the output directory, but never run as root.

**Comment by Qarj** [comment]
WebInject now gives an easy to understand message if it cannot write to the output location so people can easily figure out the issue
