### ISSUE TITLE
syntax error at webinject.pl on Centos7 x64

### ISSUE THREAD

**Issue by xoroz** [Qarj/WebInject#46]
Hello Qarj,

Thanks for the great work and keep up updating the project! I have been using it for long long time together with Centreon to monitor many websites.

**I was unable to run it on:**
CentOS Linux release 7.5.1804 x64
perl 5, version 16, subversion 3 (v5.16.3)

**ERROR:**
perl webinject.pl
syntax error at webinject.pl line 2667, near "}{"
Global symbol "$_include_file_name" requires explicit package name at webinject.pl line 2668.
Global symbol "$_include_integer_step_num" requires explicit package name at webinject.pl line 2672.
Global symbol "%_tests" requires explicit package name at webinject.pl line 2677.
syntax error at webinject.pl line 2678, near "}"
syntax error at webinject.pl line 2690, near "}"
Can't use global @_ in "my" at webinject.pl line 2715, near "= @_"
Global symbol "$_parser_raw_ref" requires explicit package name at webinject.pl line 2716.
syntax error at webinject.pl line 2724, near "}"
syntax error at webinject.pl line 2738, near "}"
webinject.pl has too many errors.

any idea what could it be?
I did install all requirements via cpan.

thanks

**Comment by Qarj** [comment]
Hi xoroz,

I don't use CentOS - but after a bit of mucking about I got the required packages installed and get the same error as you do.

By changing line 2668 to:
```
        my $_include_file_name = %{$_files_to_include }->{$_include_integer_step_num};
```
I seemed to get it to work, but that breaks newer versions of Perl!

I don't know what is wrong - it seems like it might be related to auto dereferencing - a feature that was removed in Perl 5.24. Ideally we need to figure out some code that will work in Perl 5.16.3 as well as newer versions but I'm a bit stumped for the moment. It seems to me if that line breaks, many other lines in webinject.pl like it should break also!

Let me know if that hack works for you...

**Comment by Qarj** [comment]
I may have solved this - if I rewrite to access the data as a reference instead of a hash, it seems to work on both old and new Perl. Will need further testing.

```
        my $_include_file_name = $_files_to_include->{$_include_integer_step_num};
```

**Comment by xoroz** [comment]
cool! that worked. If it works for all version, go ahead and update the main code.

thanks again for this amazing script 

cheers

**Comment by xoroz** [comment]
sry I saw now its already on latest version.

**Comment by xoroz** [comment]
ran the  selftest and got only this error:

Test:  selftest/all_core.test - 450 
include 
Verify Negative: "TEST CASE FAILED" 
Verify Positive: "TEST CASE PASSED" 
Failed Positive Verification 0
Failed Negative Verification 0
Passed HTTP Response Code Verification 
TEST CASE FAILED
Response Time = 0.306 sec

**Comment by Qarj** [comment]
Thanks for running the self test, I'm going to reopen this issue to investigate the failure...

**Comment by Qarj** [comment]
Just tested this on CentOS 7 with bundled Perl v5.16.3 - all self tests ran OK.

Tested with WebImblaze v1.1.0
