### ISSUE TITLE
WebInject 3

### ISSUE THREAD

**Issue by Qarj** [Qarj/WebInject#47]
## Create a branch for WebInject 3 then:
- [x] Remove parsing of .xml test case files
- [x] Rename description1 to step in WebInject
- [x] Rename description1 to step in WebInject-Framework
- [x] Rename description1 to step in WebInject-Selenium
- [x] Rename description1 to step in webinject-server
- [x] Rename description2 to desc in WebInject
- [x] Rename description2 to desc in WebInject-Framework
- [x] Rename description2 to desc in WebInject-Selenium
- [x] Rename description2 to desc in webinject-server
- [x] Delete WebInject-Renumber project
- [x] Update the manual for the .test file format
- [x] Remove retryfromstep feature
- [x] Merge to master
- [x] Rename this project
- [x] Rename and fix Framework project
- [x] Rename and fix Selenium project
- [x] Rename and fix server project
- [x] Rename and fix docker project
- [x] Rename and fix check project
- [x] Rename and fix Example project
- [x] Rename and fix blog examples

**Comment by cgoldberg** [comment]
this would be a great time to rename your project.  It is a fork of original "webinject" codebase with significantly changed functionality... not an upgrade to the official webinject code.

**Comment by Qarj** [comment]
Sure fair enough - I'll add thinking about a new name to the list

**Comment by xoroz** [comment]
i would leave the same name... It is how its known for. you could just call webinject3 ?

**Comment by cgoldberg** [comment]
@xoroz  It is a fork of WebInject, not the official version.  It already causes confusion, and leaving the name the same would just lead to more.  It is a different project at this point.

**Comment by cgoldberg** [comment]
also...
The name of my tool came first, but since then, a very popular banking trojan (unrelated malware) is using the same webinject name, leading to even more confusion.

**Comment by Qarj** [comment]
I've not forgotten about this by the way, I've been on leave and will be again for the next few weeks - hopefully will find some time to progress in October.

**Comment by xoroz** [comment]
Corey now I see your point.
Also version 3 changed a lot, some few new names options:
autowebinject
webautotest
pweb
.

**Comment by Qarj** [comment]
Thanks for the ideas @xoroz - it is hard work thinking of names! Ideally I want to come up with a name that is short and doesn't have zillions of results on Google...

I've got a few ideas but I think I need to give more thought.

```
webskiff     <-- 168 hits
webketch     <-- 242 hits
webdeputy    <-- 6520 hits
webavouch    <-- 29 hits
webrove      <-- 3780 hits
webgraft     <-- 2200 hits
webchisel    <-- 451 hits
webabet      <-- 2120 hits
webyegg      <-- 130 hits
webyack      <-- 135 hits
webgawk      <-- 177 hits
webincept    <-- 547 hits
```
