### ISSUE TITLE
(No output returned from plugin)

### ISSUE THREAD

**Issue by vincentdevos** [Qarj/WebInject#48]
L.S.

Can someone please help ... I'm struggling with empty Status information or as $SERVICEOUTPUT$.
I have the following basic script;

step:                   Get https://prepay.adp.nl/
url:                    https://prepay.adp.nl/
verifypositive:         loonberekening

The output from the command line states the following;

Starting WebInject Engine...

-------------------------------------------------------
Test:  ./tests/prd/NL-26_E-Prepay.test - 10
Get https://prepay.adp.nl/
Verify Positive: "loonberekening"
Passed Positive Verification
Passed HTTP Response Code Verification
TEST CASE PASSED
Response Time = 0.065 sec
-------------------------------------------------------
Start Time: Thu 25 Oct 2018, 19:22:18
Total Run Time: 0.164 seconds

Total Response Time: 0.065 seconds

Test Cases Run: 1
Test Cases Passed: 1
Test Cases Failed: 0
Verifications Passed: 3
Verifications Failed: 0

Results at: output/Results.html

But in Centreon/Nagios I get the error; (No output returned from plugin) meaning that $SERVICEOUTPUT$ is empty (See also Screendump)

![2018-10-25_19-23-38](https://user-images.githubusercontent.com/44476986/47518571-a1b75300-d88b-11e8-8b9d-b2bf09d02d5a.jpg)

**Comment by Qarj** [comment]
Hello @vincentdevos - I've never used Nagios, but it looks to me from the output you have posted you have not configured it properly for Nagios.

Your `config.xml` file needs the reporttype set as follows:
```
    <reporttype>nagios</reporttype>
```

Have a look at the output for this self test:
```
perl webinject.pl selftest/substeps/nagios.test -c selftest/substeps/nagiosconfig.xml  --no-output

WebInject CRITICAL - Nagios should see this error message |time=0.007;100;;0
```

Let me know how you get on.

**Comment by Qarj** [comment]
Note that when I used the step you provided with the Nagios self test config file, I got the output as follows:
```
webinject.pl tests/issue48.test -c selftest/substeps/nagiosconfig.xml --no-output
WebInject OK - All tests passed successfully in 0.243 seconds |time=0.243;100;;0
```

**Comment by vincentdevos** [comment]
Many, Many THANKS !!!!! Solved my issue instantly. 
Just couldn't give up looking for a solution, didn't know this (yet) ;-)

Regards,
Vincent de Vos

**Comment by Qarj** [comment]
Glad it worked, thanks for letting me know, and good luck with it!

Tim
