### ISSUE TITLE
Client-SSL-Socket-Class: IO::Socket::SSL missing in log (And therfore redirect=0 ignored)

### ISSUE THREAD

**Issue by vincentdevos** [Qarj/WebInject#49]
L.S.

I'm hoping to find another answer over here ;-) ... We have issue with the Client-SSL-Socket-Class: IO::Socket::SSL in combination with (max_redirect = 0).

On my laptop running windows my WebInject script (with al the GET steps on 302 Redirects) is working fine;

Client-SSL-Socket-Class: IO::Socket::SSL
Client-SSL-Warning: Peer certificate not verified
Client-Warning: Redirect loop detected (max_redirect = 0)
Keep-Alive: timeout=15, max=100
Title: 302 Found

On my SuSe Disaster Recovery server my WebInject script (with al the GET steps on 302 Redirects) is working fine;

Client-SSL-Socket-Class: IO::Socket::SSL
Client-SSL-Warning: Peer certificate not verified
Client-Warning: Redirect loop detected (max_redirect = 0)
Keep-Alive: timeout=15, max=100
Title: 302 Found

On my SuSe Production server my WebInject script (with al the GET steps on 302 Redirects) failes;

Client-SSL-Warning: Peer certificate not verified
Client-Warning: Redirect loop detected (max_redirect = 0)
Title: 302 Found

The difference in the logs is that on my Production server I don't see Client-SSL-Socket-Class: IO::Socket::SSL in the log, which is probably indicating that it doesn't use it.

Any thoughts ?

Regards,
Vincent de Vos

**Comment by Qarj** [comment]
I've not tried SuSe I don't think.

Have you tried?
```
sudo cpan IO::Socket
```

Might be something to Google and try install various cpan packages, if you get it working, let me know and I'll add it to installation instructions for SuSe. I've added special instructions for CentOS 7 also, but I don't think it is working 100%. All these different Linux distros makes things difficult.

**Comment by vincentdevos** [comment]
Thanks ... installed the module.
Still no client warning in the log and the redirects are still ingnored.

**Comment by vincentdevos** [comment]
Is there a minimum perl version necessary ?

**Comment by Qarj** [comment]
What version of Perl are you using? There are differences between older and newer versions of Perl in the way SSL works - they need different packages. Is the failing server using an older version of Perl? Recently I've only used 5.24+ (mostly 5.26).

**Comment by vincentdevos** [comment]
Tim, it was a Perl library as you said.
Although I don't know which one, because I just copied the entire set of Perl libraries from by DRP server to the PRD server and it was solved !!!

Now we finally started the migration from our old script (Without application Type/JSON) to the new script. 

Thanks again for helping us out and please be aware that I knwo where to find you ;-)
